apiVersion: v1
data:
  urls: "[\n  { \"url\": \"/specs/employee-service.json\", \"name\": \"Employee Service\"\
    \ }\n]\n"
kind: ConfigMap
metadata:
  name: api-docs-config
  namespace: rrhh-docs
---
apiVersion: v1
data:
  employee-service.json: "{\n  \"openapi\": \"3.0.1\",\n  \"info\": {\n    \"title\"\
    : \"Employee Service API\",\n    \"description\": \"Microservicio CRUD para gesti\\\
    u00f3n de empleados\",\n    \"contact\": {\n      \"name\": \"Aspavi\",\n    \
    \  \"url\": \"https://aspavi.com\",\n      \"email\": \"contact@aspavi.com\"\n\
    \    },\n    \"license\": {\n      \"name\": \"Apache 2.0\",\n      \"url\": \"\
    https://www.apache.org/licenses/LICENSE-2.0.html\"\n    },\n    \"version\": \"\
    1.0.0\"\n  },\n  \"servers\": [\n    {\n      \"url\": \"https://api.aspavi.com\"\
    \n    }\n  ],\n  \"paths\": {},\n  \"components\": {}\n}"
kind: ConfigMap
metadata:
  name: api-docs-specs
  namespace: rrhh-docs
