# environments/prod/keycloak/values.yaml
# Overrides de producción

replicaCount: 2

# Multi-replica: ispn with kubernetes stack for distributed cache
cache:
  stack: kubernetes

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"
