apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: realm-import-acme
  namespace: rrhh-auth
spec:
  keycloakCRName: keycloak
  realm:
    realm: rrhh-tenant-acme
    enabled: true
    displayName: "RRHH - Acme Corporation"
    sslRequired: external
    registrationAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true

    roles:
      realm:
        - name: ADMIN_RRHH
          description: "Administrador de RRHH con acceso total"
        - name: MANAGER
          description: "Manager con acceso a su departamento"
        - name: EMPLOYEE
          description: "Empleado con acceso a su propio perfil"
        - name: AUDITOR
          description: "Auditor con acceso de solo lectura"

    clients:
      - clientId: rrhh-frontend
        name: "RRHH Frontend Application"
        enabled: true
        publicClient: true
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
        rootUrl: "https://app.aspavi.com"
        redirectUris:
          - "https://app.aspavi.com/*"
          - "https://acme.aspavi.com/*"
        webOrigins:
          - "https://app.aspavi.com"
          - "https://acme.aspavi.com"
        protocol: openid-connect
        attributes:
          pkce.code.challenge.method: "S256"
        protocolMappers:
          - name: tenant_id
            protocol: openid-connect
            protocolMapper: oidc-hardcoded-claim-mapper
            config:
              claim.name: tenant_id
              claim.value: acme
              jsonType.label: String
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
          - name: realm-roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            config:
              claim.name: roles
              jsonType.label: String
              multivalued: "true"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"

      - clientId: rrhh-employee-service
        name: "Employee Service"
        enabled: true
        publicClient: false
        standardFlowEnabled: false
        serviceAccountsEnabled: true
        clientAuthenticatorType: client-secret
        protocol: openid-connect
        protocolMappers:
          - name: tenant_id
            protocol: openid-connect
            protocolMapper: oidc-hardcoded-claim-mapper
            config:
              claim.name: tenant_id
              claim.value: acme
              jsonType.label: String
              id.token.claim: "true"
              access.token.claim: "true"
