apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vmorera/aspavi-infra.git
    targetRevision: master
    path: apps/events-service
  destination:
    server: https://kubernetes.default.svc
    namespace: rrhh-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
