apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/vmorera/aspavi-infra.git
    targetRevision: master
    path: apps/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: rrhh-auth
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
