# helm/argocd/values.yaml
# Valores base comunes a todos los entornos

configs:
  params:
    server.insecure: true   # Traefik gestiona TLS, ArgoCD no necesita su propio TLS

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.aspavi.com
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.aspavi.com
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
