# helm/argocd/values.yaml
# Valores base comunes a todos los entornos

configs:
  params:
    server.insecure: true   # Traefik gestiona TLS, ArgoCD no necesita su propio TLS

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.aspavi.com
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
