# helm/argocd/values.yaml
# Valores base comunes a todos los entornos

configs:
  params:
    server.insecure: true   # Traefik gestiona TLS, ArgoCD no necesita su propio TLS
  cm:
    url: https://argocd.aspavi.com
    accounts.aspatoal: apiKey, login
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.aspavi.com/realms/master
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
      groupsClaim: groups
  rbac:
    policy.csv: |
      g, aspatoal, role:admin
      g, /argocd-admins, role:admin

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.aspavi.com
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/common-name: "argocd.aspavi.com"
